### PR TITLE
Sync scintilua repo

### PR DESCRIPTION
**Pull request by mcepl**
Couple of upgraded lexers.

### CODE REVIEW

**Comment by Nomarian** [comment]
There's some typescript changes, scintilua repo is the one handling that one.


Why delete gemini?

**Comment by Nomarian** [comment]
typescript will probably get wiped by next sync.

**Comment by mcepl** [comment]
> typescript will probably get wiped by next sync.

Why? It is present upstream? https://github.com/orbitalquark/scintillua/blob/default/lexers/typescript.lua

Also, working upstream on https://github.com/orbitalquark/scintillua/pull/71 and https://github.com/orbitalquark/scintillua/pull/70

**Comment by Nomarian** [comment]
its present upstream but its not the same as this one, the only method I see of this working is if the lexers get continually replaced with the upstream version. and then fix/adjust lexer.lua so that it works on vis.

**Comment by mcepl** [comment]
> its present upstream but its not the same as this one, the only method I see of this working is if the lexers get continually replaced with the upstream version. and then fix/adjust lexer.lua so that it works on vis.

And why not to push our changes upstream, the maintainer there seemed rather responsive?

**Comment by Nomarian** [comment]
Doesn't want 4 of those lexers, lexer.lua does not work upstream (scite wants everything global), go seems the same as the upstream version, the only thing that is different is typescript, which idk where it came from, so that should go upstream I guess?

**Comment by mcepl** [comment]
> Doesn't want 4 of those lexers,

Which ones?

- [X] typescript.lua identical to the upstream
- [ ] strace.lua https://github.com/orbitalquark/scintillua/pull/73
- [ ] gemini.lua https://github.com/orbitalquark/scintillua/pull/74
- [ ] git-rebase.lua https://github.com/orbitalquark/scintillua/pull/72

> lexer.lua does not work upstream (scite wants everything global),

I don’t understand. I have this diff:
```diff
--- /home/matej/repos/tmp/scintillua/lexers/lexer.lua	2022-06-29 11:16:41.273312518 +0200
+++ /usr/share/vis/lexer.lua	2022-07-20 20:28:08.000000000 +0200
@@ -1,6 +1,7 @@
 -- Copyright 2006-2022 Mitchell. See LICENSE.
 
 local M = {}
+lpeg = require'lpeg'
 
 --[=[ This comment is for LuaDoc.
 ---
@@ -804,34 +805,12 @@
 --   This is an alias for `lexer.property['fold.line.groups'] = '1|0'`.
 module('lexer')]=]
 
-if not require then
-  -- Substitute for Lua's require() function, which does not require the package module to
-  -- be loaded.
-  -- Note: all modules must be in the global namespace, which is the case in LexerLPeg's default
-  -- Lua State.
-  function require(name) return name == 'lexer' and M or _G[name] end
-end
-
 local lpeg = require('lpeg')
 local lpeg_P, lpeg_R, lpeg_S, lpeg_V = lpeg.P, lpeg.R, lpeg.S, lpeg.V
 local lpeg_Ct, lpeg_Cc, lpeg_Cp = lpeg.Ct, lpeg.Cc, lpeg.Cp
 local lpeg_Cmt, lpeg_C = lpeg.Cmt, lpeg.C
 local lpeg_match = lpeg.match
 
--- Searches for the given *name* in the given *path*.
--- This is a safe implementation of Lua 5.2's `package.searchpath()` function that does not
--- require the package module to be loaded.
-local function searchpath(name, path)
-  local tried = {}
-  for part in path:gmatch('[^;]+') do
-    local filename = part:gsub('%?', name)
-    local ok, errmsg = loadfile(filename)
-    if ok or not errmsg:find('cannot open') then return filename end
-    tried[#tried + 1] = string.format("no file '%s'", filename)
-  end
-  return nil, table.concat(tried, '\n')
-end
-
 ---
 -- Map of color name strings to color values in `0xBBGGRR` or `"#RRGGBB"` format.
 -- Note: for applications running within a terminal emulator, only 16 color values are recognized,
@@ -1451,6 +1430,11 @@
 --   purposes). The default value is `false`.
 -- @return lexer object
 -- @name load
+
+-- finds the vis installed lexer
+-- TODO: include ~/.config/vis or ~/.vis
+local LEXERPATH1 = package.searchpath("lexers/null", package.path):gsub("/null%.lua$","")
+
 function M.load(name, alt_name, cache)
   if cache and lexers[alt_name or name] then return lexers[alt_name or name] end
 
@@ -1458,7 +1442,7 @@
   -- `property_expanded` tables do not exist (they are not useful). Create them in order prevent
   -- errors from occurring.
   if not M.property then
-    M.property = setmetatable({['lexer.lpeg.home'] = package.path:gsub('/%?%.lua', '')}, {
+    M.property = setmetatable( {['lexer.lpeg.home'] = LEXERPATH1 }, {
       __index = function() return '' end,
       __newindex = function(t, k, v) rawset(t, k, tostring(v)) end
     })
@@ -1479,8 +1463,8 @@
   -- whitespace style names. Note that loading embedded lexers changes `WHITESPACE` again,
   -- so when adding it later, do not reference the potentially incorrect value.
   M.WHITESPACE = (alt_name or name) .. '_whitespace'
-  local path = M.property['lexer.lpeg.home']:gsub(';', '/?.lua;') .. '/?.lua'
-  local lexer = dofile(assert(searchpath(name, path)))
+  local lexer = require("lexers/" .. name)
+  -- local lexer = dofile(assert( package.searchpath(name, LEXERPATH2) ))
   assert(lexer, string.format("'%s.lua' did not return a lexer", name))
   if alt_name then lexer._NAME = alt_name end
   if not getmetatable(lexer) or lexer._LEGACY then
```

Obviously there are differences, but I don’t see anything which couldn’t be agreed upon or parametrized somehow.

**Comment by Nomarian** [comment]
https://github.com/orbitalquark/scintillua/issues/68


Did not want to merge the lexers: strace, gemini, dsv, git-rebase.


textadept works with lua 5.1, so it recreates package.searchpath, I like package.searchpath and many of the features of post 5.1 (its 15 years old now.) it also overwrites require. I like the way lua handles packages and knowing what require does in a standard manner. if you need another way to handle packages in lua, you do it via the package.loaders. Which I don't think can be done in scintilua. but I haven't asked.

**Comment by Nomarian** [comment]
BUG: html lexers are broken.

**Comment by mcepl** [comment]
> BUG: html lexers are broken.

Define “broken”.

**Comment by Nomarian** [comment]
Well, it doesn't seem to recognize anything?

**Pull request merged**
